# Generated by Django 5.0 on 2023-12-12 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='user_type',
            field=models.CharField(choices=[('ALUMNO', 'Alumno'), ('DOCENTE', 'Docente')], default='ALUMNO', max_length=7),
        ),
    ]
