# Generated by Django 5.0 on 2023-12-12 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuario_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamo',
            old_name='id_del_libro',
            new_name='libro',
        ),
        migrations.RenameField(
            model_name='prestamo',
            old_name='id_del_usuario',
            new_name='usuario',
        ),
    ]
