# Generated by Django 5.0 on 2023-12-12 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_prestamo_fecha_de_devolucion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_de_prestamo',
            field=models.DateField(blank=True, null=True),
        ),
    ]
