# Generated by Django 5.0 on 2023-12-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_prestamo_fecha_de_prestamo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rut',
            field=models.CharField(default='11.111.111-1', max_length=20),
            preserve_default=False,
        ),
    ]
