# Generated by Django 5.0 on 2023-12-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_usuario_rut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='fecha_de_devolucion',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='fecha_de_prestamo',
        ),
        migrations.AddField(
            model_name='libro',
            name='prestado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='fecha_devolucion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='fecha_prestamo',
            field=models.DateTimeField(auto_now_add=True, default='2023-12-12 12:00:00'),
            preserve_default=False,
        ),
    ]
