# Generated by Django 5.0 on 2023-12-12 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_prestamo_fecha_de_devolucion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='multa_pagada',
            field=models.BooleanField(default=False),
        ),
    ]
